# export PS1='[\w]$(__git_ps1 "(%s)")$ '
# export PS1='\h:\W \u$(__git_ps1 " (%s)")\$ '
# export PATH=/usr/local/bin:/usr/local/sbin:$PATH

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

alias l='ls -alh'

# alias start_mongod='mongod -f /usr/local/Cellar/mongodb/2.0.3-x86_64/mongod.conf'
# alias start_activemq='/Users/mtardivo/code/java/apache-activemq-5.5.1/bin/activemq start'
# alias stop_activemq='/Users/mtardivo/code/java/apache-activemq-5.5.1/bin/activemq stop'
# alias start_http='python -m SimpleHTTPServer 8000'

# alias memcached_load="launchctl load -w /usr/local/Cellar/memcached/1.4.13/homebrew.mxcl.memcached.plist"
# alias memcached_unload="launchctl unload -w /usr/local/Cellar/memcached/1.4.13/homebrew.mxcl.memcached.plist"
# alias mysql_load="launchctl load -w /usr/local/Cellar/mysql/5.5.20/homebrew.mxcl.mysql.plist"
# alias mysql_unload="launchctl unload -w /usr/local/Cellar/mysql/5.5.20/homebrew.mxcl.mysql.plist"
# alias postgres_load="launchctl load -w /usr/local/Cellar/postgresql/9.1.3/homebrew.mxcl.postgresql.plist"
# alias postgres_unload="launchctl unload -w /usr/local/Cellar/postgresql/9.1.3/homebrew.mxcl.postgresql.plist"

alias postgres_load="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start"
alias postgres_unload="pg_ctl -D /usr/local/var/postgres stop -s -m fast"

source ~/.git-completion.sh
source ~/.git-prompt.sh

stty werase undef
bind '"\C-w": backward-kill-word'

export CLICOLOR=1
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWUPSTREAM="auto"

export PS1='\n\u@\h:\w$(__git_ps1 " (%s)")\n\$ '
export PATH=/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:$PATH

export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home

if [ -d $HOME/.rbenv ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi
